# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
pr: none

pool:
  name: 'fss-self'

steps:
- task: UseDotNet@2
  displayName: 'Setup .NET8 SDK Environment'
  inputs:
    version: 8.x

- task: DotNetCoreCLI@2
  displayName: 'Install WASM Workload'
  inputs:
    command: 'custom'
    custom: 'workload'
    arguments: 'install wasm-tools'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Restore'
  inputs:
    command: 'restore'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.sln'
    arguments: '-c Release -o "$(Build.ArtifactStagingDirectory)" /p:Platform="Any CPU"'
    zipAfterPublish: false
    modifyOutputPath: false